runtime: java17
#instance_class: F1
instance_class: B1
env: flex
#runtime_config:
#  jdk: openjdk17
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1