name: Qwiet

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  ngsast-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Download the Qwiet CLI and set permissions
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Package with Maven
        run: mvn clean package

      - name: NextGen Static Analysis
        run: ${GITHUB_WORKSPACE}/sl analyze --app ShiftLeftJava --tag branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} --vcs-prefix-correction "io/shiftleft=src/main/java/" --java $(pwd)/target/yourJarFileName.jar

        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}